import type { IdCardCategory, IdCardComponent, IdCardLayoutV1 } from './layout'
import { parseIdCardLayout } from './layout'

export interface IdCardStarter {
  key: string
  name: string
  category: IdCardCategory
  description: string
  tags: string[]
  layout: IdCardLayoutV1
}

function card(canvas: IdCardLayoutV1['canvas'], components: IdCardComponent[]): IdCardLayoutV1 {
  const parsed = parseIdCardLayout({ version: 1, canvas, components })
  if (!parsed.ok) {
    throw new Error(parsed.error)
  }
  return parsed.layout
}

const classicStudent = card(
  { widthMm: 54, heightMm: 86, background: { type: 'solid', color: '#f7f4ee' } },
  [
    { id: 'header', type: 'shape', shape: 'rect', xMm: 0, yMm: 0, widthMm: 54, heightMm: 22, fill: '#1e3a5f' },
    { id: 'gold-line', type: 'shape', shape: 'rect', xMm: 0, yMm: 22, widthMm: 54, heightMm: 1.4, fill: '#c9a227' },
    { id: 'footer-bar', type: 'shape', shape: 'rect', xMm: 0, yMm: 80, widthMm: 54, heightMm: 6, fill: '#1e3a5f' },
    { id: 'logo', type: 'logo', shape: 'circle', xMm: 4, yMm: 4, widthMm: 12, heightMm: 12 },
    {
      id: 'school-name',
      type: 'text',
      field: 'school.name',
      xMm: 18,
      yMm: 5,
      widthMm: 32,
      heightMm: 8,
      fontSizeMm: 2.8,
      fontWeight: 700,
      color: '#ffffff',
      align: 'left',
    },
    {
      id: 'card-label',
      type: 'text',
      text: 'STUDENT IDENTITY',
      xMm: 18,
      yMm: 13,
      widthMm: 32,
      heightMm: 5,
      fontSizeMm: 1.8,
      color: '#e7d7a3',
      letterSpacingMm: 0.15,
    },
    { id: 'photo', type: 'photo', shape: 'rounded', xMm: 16, yMm: 28, widthMm: 22, heightMm: 26, field: 'student.photoUrl' },
    {
      id: 'student-name',
      type: 'text',
      field: 'student.fullName',
      xMm: 4,
      yMm: 56,
      widthMm: 46,
      heightMm: 7,
      fontSizeMm: 3.2,
      fontWeight: 700,
      color: '#1e3a5f',
      align: 'center',
    },
    {
      id: 'class-line',
      type: 'text',
      text: '{{student.className}} · Section {{student.sectionName}}',
      xMm: 4,
      yMm: 63,
      widthMm: 46,
      heightMm: 5,
      fontSizeMm: 2.1,
      color: '#5c5346',
      align: 'center',
    },
    {
      id: 'admission',
      type: 'text',
      text: 'Adm {{student.admissionNo}}',
      xMm: 4,
      yMm: 70,
      widthMm: 28,
      heightMm: 8,
      fontSizeMm: 2,
      color: '#1e3a5f',
    },
    { id: 'qr', type: 'qr', field: 'card.qrPayload', xMm: 36, yMm: 68, widthMm: 14, heightMm: 14 },
    {
      id: 'address',
      type: 'text',
      field: 'school.address',
      xMm: 3,
      yMm: 81,
      widthMm: 48,
      heightMm: 4,
      fontSizeMm: 1.6,
      color: '#e7d7a3',
      align: 'center',
    },
  ],
)

const auroraStudent = card(
  {
    widthMm: 54,
    heightMm: 86,
    background: {
      type: 'linear-gradient',
      color: '#0f766e',
      gradientFrom: '#0f766e',
      gradientTo: '#1e3a8a',
      gradientAngleDeg: 165,
    },
  },
  [
    { id: 'panel', type: 'shape', shape: 'rounded-rect', xMm: 3, yMm: 3, widthMm: 48, heightMm: 80, fill: '#ffffff', radiusMm: 3 },
    { id: 'accent', type: 'shape', shape: 'rect', xMm: 3, yMm: 3, widthMm: 48, heightMm: 6, fill: '#14b8a6' },
    { id: 'logo', type: 'logo', shape: 'rounded', xMm: 7, yMm: 12, widthMm: 10, heightMm: 10 },
    {
      id: 'school-name',
      type: 'text',
      field: 'school.name',
      xMm: 19,
      yMm: 13,
      widthMm: 28,
      heightMm: 8,
      fontSizeMm: 2.6,
      fontWeight: 700,
      color: '#0f172a',
    },
    { id: 'photo', type: 'photo', shape: 'circle', xMm: 16, yMm: 26, widthMm: 22, heightMm: 22, field: 'student.photoUrl' },
    {
      id: 'student-name',
      type: 'text',
      field: 'student.fullName',
      xMm: 6,
      yMm: 50,
      widthMm: 42,
      heightMm: 7,
      fontSizeMm: 3.1,
      fontWeight: 700,
      color: '#0f766e',
      align: 'center',
    },
    {
      id: 'roll',
      type: 'text',
      text: 'Roll {{student.rollNo}}  ·  {{student.className}}-{{student.sectionName}}',
      xMm: 6,
      yMm: 57,
      widthMm: 42,
      heightMm: 5,
      fontSizeMm: 2,
      color: '#475569',
      align: 'center',
    },
    {
      id: 'blood',
      type: 'text',
      text: 'Blood {{student.bloodGroup}}',
      xMm: 7,
      yMm: 64,
      widthMm: 22,
      heightMm: 5,
      fontSizeMm: 2,
      color: '#0f172a',
    },
    {
      id: 'dob',
      type: 'text',
      text: 'DOB {{student.dateOfBirth}}',
      xMm: 7,
      yMm: 70,
      widthMm: 24,
      heightMm: 5,
      fontSizeMm: 1.9,
      color: '#0f172a',
    },
    { id: 'qr', type: 'qr', field: 'card.qrPayload', xMm: 34, yMm: 64, widthMm: 13, heightMm: 13 },
  ],
)

const landscapeStudent = card(
  { widthMm: 86, heightMm: 54, background: { type: 'solid', color: '#ffffff' } },
  [
    { id: 'stripe', type: 'shape', shape: 'rect', xMm: 0, yMm: 0, widthMm: 8, heightMm: 54, fill: '#1d4ed8' },
    { id: 'top', type: 'shape', shape: 'rect', xMm: 8, yMm: 0, widthMm: 78, heightMm: 12, fill: '#eff6ff' },
    { id: 'logo', type: 'logo', shape: 'rounded', xMm: 12, yMm: 2, widthMm: 8, heightMm: 8 },
    {
      id: 'school-name',
      type: 'text',
      field: 'school.name',
      xMm: 22,
      yMm: 3,
      widthMm: 58,
      heightMm: 7,
      fontSizeMm: 3,
      fontWeight: 700,
      color: '#1e3a8a',
    },
    { id: 'photo', type: 'photo', shape: 'rounded', xMm: 12, yMm: 16, widthMm: 20, heightMm: 26, field: 'student.photoUrl' },
    {
      id: 'student-name',
      type: 'text',
      field: 'student.fullName',
      xMm: 36,
      yMm: 16,
      widthMm: 32,
      heightMm: 8,
      fontSizeMm: 3.4,
      fontWeight: 700,
      color: '#0f172a',
    },
    {
      id: 'class-line',
      type: 'text',
      text: '{{student.className}} {{student.sectionName}}  ·  Roll {{student.rollNo}}',
      xMm: 36,
      yMm: 25,
      widthMm: 32,
      heightMm: 6,
      fontSizeMm: 2.1,
      color: '#334155',
    },
    {
      id: 'admission',
      type: 'text',
      field: 'student.admissionNo',
      xMm: 36,
      yMm: 32,
      widthMm: 32,
      heightMm: 5,
      fontSizeMm: 2,
      color: '#1d4ed8',
    },
    {
      id: 'phone',
      type: 'text',
      text: 'Guardian {{guardian.phone}}',
      xMm: 36,
      yMm: 38,
      widthMm: 32,
      heightMm: 5,
      fontSizeMm: 1.8,
      color: '#64748b',
    },
    { id: 'qr', type: 'qr', field: 'card.qrPayload', xMm: 70, yMm: 16, widthMm: 12, heightMm: 12 },
    {
      id: 'address',
      type: 'text',
      field: 'school.address',
      xMm: 12,
      yMm: 46,
      widthMm: 70,
      heightMm: 6,
      fontSizeMm: 1.7,
      color: '#64748b',
    },
  ],
)

const facultyStaff = card(
  { widthMm: 54, heightMm: 86, background: { type: 'solid', color: '#111827' } },
  [
    { id: 'inner', type: 'shape', shape: 'rect', xMm: 2, yMm: 2, widthMm: 50, heightMm: 82, fill: '#1f2937' },
    { id: 'gold', type: 'shape', shape: 'rect', xMm: 2, yMm: 20, widthMm: 50, heightMm: 0.8, fill: '#d4af37' },
    { id: 'logo', type: 'logo', shape: 'circle', xMm: 21, yMm: 5, widthMm: 12, heightMm: 12 },
    {
      id: 'school-name',
      type: 'text',
      field: 'school.name',
      xMm: 4,
      yMm: 23,
      widthMm: 46,
      heightMm: 6,
      fontSizeMm: 2.2,
      fontWeight: 600,
      color: '#d4af37',
      align: 'center',
      uppercase: true,
    },
    { id: 'photo', type: 'photo', shape: 'circle', xMm: 16, yMm: 31, widthMm: 22, heightMm: 22, field: 'staff.photoUrl' },
    {
      id: 'staff-name',
      type: 'text',
      field: 'staff.fullName',
      xMm: 4,
      yMm: 55,
      widthMm: 46,
      heightMm: 7,
      fontSizeMm: 3.1,
      fontWeight: 700,
      color: '#f9fafb',
      align: 'center',
    },
    {
      id: 'designation',
      type: 'text',
      field: 'staff.designation',
      xMm: 4,
      yMm: 62,
      widthMm: 46,
      heightMm: 5,
      fontSizeMm: 2.1,
      color: '#d4af37',
      align: 'center',
    },
    {
      id: 'employee',
      type: 'text',
      text: '{{staff.employeeId}}  ·  {{staff.department}}',
      xMm: 4,
      yMm: 68,
      widthMm: 46,
      heightMm: 5,
      fontSizeMm: 1.9,
      color: '#d1d5db',
      align: 'center',
    },
    { id: 'qr', type: 'qr', field: 'card.qrPayload', xMm: 20, yMm: 74, widthMm: 14, heightMm: 14 },
  ],
)

const teacherLandscape = card(
  { widthMm: 86, heightMm: 54, background: { type: 'solid', color: '#f8fafc' } },
  [
    { id: 'left', type: 'shape', shape: 'rect', xMm: 0, yMm: 0, widthMm: 32, heightMm: 54, fill: '#0f172a' },
    { id: 'photo', type: 'photo', shape: 'circle', xMm: 6, yMm: 8, widthMm: 20, heightMm: 20, field: 'staff.photoUrl' },
    {
      id: 'role',
      type: 'text',
      text: 'FACULTY',
      xMm: 4,
      yMm: 32,
      widthMm: 24,
      heightMm: 5,
      fontSizeMm: 2,
      color: '#94a3b8',
      align: 'center',
      letterSpacingMm: 0.2,
    },
    {
      id: 'staff-name-left',
      type: 'text',
      field: 'staff.fullName',
      xMm: 3,
      yMm: 38,
      widthMm: 26,
      heightMm: 10,
      fontSizeMm: 2.6,
      fontWeight: 700,
      color: '#ffffff',
      align: 'center',
    },
    { id: 'logo', type: 'logo', shape: 'rounded', xMm: 38, yMm: 6, widthMm: 10, heightMm: 10 },
    {
      id: 'school-name',
      type: 'text',
      field: 'school.name',
      xMm: 50,
      yMm: 7,
      widthMm: 32,
      heightMm: 8,
      fontSizeMm: 2.6,
      fontWeight: 700,
      color: '#0f172a',
    },
    {
      id: 'designation',
      type: 'text',
      field: 'staff.designation',
      xMm: 38,
      yMm: 20,
      widthMm: 44,
      heightMm: 6,
      fontSizeMm: 2.4,
      fontWeight: 600,
      color: '#1e3a5f',
    },
    {
      id: 'department',
      type: 'text',
      field: 'staff.department',
      xMm: 38,
      yMm: 27,
      widthMm: 30,
      heightMm: 5,
      fontSizeMm: 2,
      color: '#475569',
    },
    {
      id: 'employee',
      type: 'text',
      field: 'staff.employeeId',
      xMm: 38,
      yMm: 34,
      widthMm: 30,
      heightMm: 5,
      fontSizeMm: 2,
      color: '#0f172a',
    },
    { id: 'qr', type: 'qr', field: 'card.qrPayload', xMm: 70, yMm: 32, widthMm: 12, heightMm: 12 },
    {
      id: 'principal',
      type: 'text',
      text: 'Principal {{school.principalName}}',
      xMm: 38,
      yMm: 46,
      widthMm: 44,
      heightMm: 5,
      fontSizeMm: 1.7,
      color: '#64748b',
    },
  ],
)

const visitorDayPass = card(
  { widthMm: 86, heightMm: 54, background: { type: 'solid', color: '#fff7ed' } },
  [
    { id: 'banner', type: 'shape', shape: 'rect', xMm: 0, yMm: 0, widthMm: 86, heightMm: 16, fill: '#c2410c' },
    {
      id: 'visitor-label',
      type: 'text',
      text: 'VISITOR',
      xMm: 4,
      yMm: 3,
      widthMm: 50,
      heightMm: 10,
      fontSizeMm: 5.5,
      fontWeight: 700,
      color: '#fff7ed',
      letterSpacingMm: 0.4,
    },
    { id: 'logo', type: 'logo', shape: 'rounded', xMm: 72, yMm: 3, widthMm: 10, heightMm: 10 },
    {
      id: 'school-name',
      type: 'text',
      field: 'school.name',
      xMm: 4,
      yMm: 20,
      widthMm: 54,
      heightMm: 6,
      fontSizeMm: 2.4,
      fontWeight: 600,
      color: '#9a3412',
    },
    {
      id: 'visitor-name',
      type: 'text',
      field: 'visitor.fullName',
      xMm: 4,
      yMm: 28,
      widthMm: 54,
      heightMm: 8,
      fontSizeMm: 3.6,
      fontWeight: 700,
      color: '#1c1917',
    },
    {
      id: 'purpose',
      type: 'text',
      text: 'Purpose  {{visitor.purpose}}',
      xMm: 4,
      yMm: 38,
      widthMm: 54,
      heightMm: 5,
      fontSizeMm: 2.1,
      color: '#57534e',
    },
    {
      id: 'valid',
      type: 'text',
      text: 'Valid on  {{visitor.validOn}}',
      xMm: 4,
      yMm: 44,
      widthMm: 54,
      heightMm: 5,
      fontSizeMm: 2.1,
      color: '#57534e',
    },
    { id: 'qr', type: 'qr', field: 'card.qrPayload', xMm: 68, yMm: 22, widthMm: 14, heightMm: 14 },
    {
      id: 'escort',
      type: 'text',
      text: 'Return this pass at the office',
      xMm: 62,
      yMm: 44,
      widthMm: 22,
      heightMm: 8,
      fontSizeMm: 1.6,
      color: '#c2410c',
      align: 'center',
    },
  ],
)

const primaryCrest = card(
  { widthMm: 54, heightMm: 86, background: { type: 'solid', color: '#e0f2fe' } },
  [
    { id: 'header', type: 'shape', shape: 'ellipse', xMm: -10, yMm: -16, widthMm: 74, heightMm: 40, fill: '#0284c7' },
    { id: 'logo', type: 'logo', shape: 'circle', xMm: 20, yMm: 6, widthMm: 14, heightMm: 14 },
    {
      id: 'school-name',
      type: 'text',
      field: 'school.name',
      xMm: 4,
      yMm: 22,
      widthMm: 46,
      heightMm: 8,
      fontSizeMm: 2.5,
      fontWeight: 700,
      color: '#ffffff',
      align: 'center',
    },
    { id: 'photo', type: 'photo', shape: 'circle', xMm: 15, yMm: 34, widthMm: 24, heightMm: 24, field: 'student.photoUrl' },
    {
      id: 'student-name',
      type: 'text',
      field: 'student.fullName',
      xMm: 4,
      yMm: 60,
      widthMm: 46,
      heightMm: 7,
      fontSizeMm: 3.2,
      fontWeight: 700,
      color: '#0c4a6e',
      align: 'center',
    },
    {
      id: 'class-line',
      type: 'text',
      text: '{{student.className}}  {{student.sectionName}}',
      xMm: 4,
      yMm: 67,
      widthMm: 46,
      heightMm: 5,
      fontSizeMm: 2.2,
      color: '#0369a1',
      align: 'center',
    },
    {
      id: 'admission',
      type: 'text',
      field: 'student.admissionNo',
      xMm: 4,
      yMm: 73,
      widthMm: 30,
      heightMm: 5,
      fontSizeMm: 1.9,
      color: '#075985',
    },
    { id: 'qr', type: 'qr', field: 'card.qrPayload', xMm: 36, yMm: 72, widthMm: 12, heightMm: 12 },
  ],
)

const officialBoard = card(
  { widthMm: 54, heightMm: 86, background: { type: 'solid', color: '#faf6ef' } },
  [
    { id: 'outer', type: 'shape', shape: 'rect', xMm: 2, yMm: 2, widthMm: 50, heightMm: 82, fill: '#ffffff', stroke: '#1e3a5f', strokeWidthMm: 0.5 },
    { id: 'header', type: 'shape', shape: 'rect', xMm: 2, yMm: 2, widthMm: 50, heightMm: 16, fill: '#1e3a5f' },
    { id: 'logo', type: 'logo', shape: 'rect', xMm: 5, yMm: 4, widthMm: 10, heightMm: 10 },
    {
      id: 'school-name',
      type: 'text',
      field: 'school.name',
      xMm: 16,
      yMm: 4,
      widthMm: 34,
      heightMm: 7,
      fontSizeMm: 2.4,
      fontWeight: 700,
      color: '#ffffff',
    },
    {
      id: 'subtitle',
      type: 'text',
      text: 'IDENTITY CARD',
      xMm: 16,
      yMm: 11,
      widthMm: 34,
      heightMm: 5,
      fontSizeMm: 1.7,
      color: '#cbd5e1',
      letterSpacingMm: 0.12,
    },
    { id: 'photo', type: 'photo', shape: 'rect', xMm: 6, yMm: 22, widthMm: 18, heightMm: 22, field: 'student.photoUrl' },
    {
      id: 'student-name',
      type: 'text',
      field: 'student.fullName',
      xMm: 26,
      yMm: 22,
      widthMm: 24,
      heightMm: 8,
      fontSizeMm: 2.6,
      fontWeight: 700,
      color: '#1e3a5f',
    },
    {
      id: 'class-line',
      type: 'text',
      text: '{{student.className}} / {{student.sectionName}}',
      xMm: 26,
      yMm: 31,
      widthMm: 24,
      heightMm: 5,
      fontSizeMm: 1.9,
      color: '#334155',
    },
    {
      id: 'roll',
      type: 'text',
      text: 'Roll {{student.rollNo}}',
      xMm: 26,
      yMm: 37,
      widthMm: 24,
      heightMm: 5,
      fontSizeMm: 1.9,
      color: '#334155',
    },
    {
      id: 'admission',
      type: 'text',
      text: 'Adm. No.  {{student.admissionNo}}',
      xMm: 6,
      yMm: 47,
      widthMm: 42,
      heightMm: 5,
      fontSizeMm: 2,
      color: '#1e3a5f',
    },
    {
      id: 'dob',
      type: 'text',
      text: 'Date of birth  {{student.dateOfBirth}}',
      xMm: 6,
      yMm: 53,
      widthMm: 42,
      heightMm: 5,
      fontSizeMm: 1.9,
      color: '#334155',
    },
    {
      id: 'blood',
      type: 'text',
      text: 'Blood group  {{student.bloodGroup}}',
      xMm: 6,
      yMm: 59,
      widthMm: 28,
      heightMm: 5,
      fontSizeMm: 1.9,
      color: '#334155',
    },
    {
      id: 'phone',
      type: 'text',
      text: 'Guardian  {{guardian.phone}}',
      xMm: 6,
      yMm: 65,
      widthMm: 42,
      heightMm: 5,
      fontSizeMm: 1.8,
      color: '#334155',
    },
    { id: 'qr', type: 'qr', field: 'card.qrPayload', xMm: 36, yMm: 70, widthMm: 12, heightMm: 12 },
    {
      id: 'principal',
      type: 'text',
      text: 'Principal {{school.principalName}}',
      xMm: 6,
      yMm: 74,
      widthMm: 28,
      heightMm: 8,
      fontSizeMm: 1.6,
      color: '#64748b',
    },
  ],
)

export const ID_CARD_STARTERS: IdCardStarter[] = [
  {
    key: 'classic-student',
    name: 'Classic Student',
    category: 'student',
    description: 'Navy and gold portrait card with school header and admission QR.',
    tags: ['portrait', 'navy', 'cr80', 'secondary'],
    layout: classicStudent,
  },
  {
    key: 'aurora-student',
    name: 'Aurora Student',
    category: 'student',
    description: 'Teal-to-indigo gradient portrait with circular photo.',
    tags: ['portrait', 'gradient', 'modern'],
    layout: auroraStudent,
  },
  {
    key: 'landscape-student',
    name: 'Compact Landscape',
    category: 'student',
    description: 'Horizontal CR80 student card with photo, class, and guardian phone.',
    tags: ['landscape', 'compact', 'cr80'],
    layout: landscapeStudent,
  },
  {
    key: 'faculty-staff',
    name: 'Faculty Crest',
    category: 'staff',
    description: 'Dark charcoal staff card with gold accents.',
    tags: ['portrait', 'staff', 'formal'],
    layout: facultyStaff,
  },
  {
    key: 'teacher-landscape',
    name: 'Teacher Landscape',
    category: 'staff',
    description: 'Horizontal faculty card with photo panel and employee id.',
    tags: ['landscape', 'teacher', 'staff'],
    layout: teacherLandscape,
  },
  {
    key: 'visitor-day-pass',
    name: 'Visitor Day Pass',
    category: 'visitor',
    description: 'High-contrast visitor pass with purpose and validity date.',
    tags: ['landscape', 'visitor', 'pass'],
    layout: visitorDayPass,
  },
  {
    key: 'primary-crest',
    name: 'Primary Crest',
    category: 'student',
    description: 'Soft blue portrait for younger students with a circular photo.',
    tags: ['portrait', 'primary', 'rounded'],
    layout: primaryCrest,
  },
  {
    key: 'official-board',
    name: 'Official Board',
    category: 'student',
    description: 'Formal bordered card with DOB, blood group, and principal line.',
    tags: ['portrait', 'formal', 'board'],
    layout: officialBoard,
  },
]

export const ID_CARD_STARTER_COUNT = ID_CARD_STARTERS.length

export function getIdCardStarter(key: string): IdCardStarter | undefined {
  return ID_CARD_STARTERS.find((starter) => starter.key === key)
}

export function filterIdCardStarters(query: string, category: 'all' | IdCardCategory): IdCardStarter[] {
  const q = query.trim().toLowerCase()
  return ID_CARD_STARTERS.filter((starter) => {
    if (category !== 'all' && starter.category !== category) return false
    if (!q) return true
    const haystack = [starter.name, starter.category, starter.description, ...starter.tags].join(' ').toLowerCase()
    return haystack.includes(q)
  })
}
